#!/bin/bash

function make_changes {
	echo $'editing ' $1
	sed -i 's/UINT32/uint32_t/g' $1
	sed -i 's/UINT16/uint16_t/g' $1
	sed -i 's/UINT8/uint8_t/g' $1
	sed -i 's/INT32/int32_t/g' $1
	sed -i 's/INT16/int16_t/g' $1
	sed -i 's/INT8/int8_t/g' $1
	sed -i 's/DAR_Basic_Defs/stdint/g' $1
	sed -i 's/DAR_RegDefs/rio_standard/g' $1
	sed -i 's/VOID/void/g' $1
	sed -i 's/BOOL/bool/g' $1
	sed -i 's/TRUE/true/g' $1
	sed -i 's/FALSE/false/g' $1

	sed -i 's/RIO_DEV_ID_CAR/RIO_DEV_IDENT/g' $1
	sed -i 's/RIO_DEV_INFO_CAR/RIO_DEV_INF/g' $1

	sed -i 's/RIO_ASBLY_ID_CAR/RIO_ASSY_ID/g' $1
	sed -i 's/RIO_ASBLY_INFO_CAR/RIO_ASSY_INF/g' $1
	sed -i 's/RIO_ASBLY_INFO_ASBLY_REV/RIO_ASSY_INF_ASSY_REV/g' $1

	sed -i 's/RIO_FEATURES/RIO_PE_FEAT_T/g' $1
	sed -i 's/RIO_PROC_ELEM_FEAT_CAR/RIO_PE_FEAT/g' $1
	sed -i 's/RIO_PROC_ELEM_FEAT_EXT_FEA/RIO_PE_FEAT_EFB_VALID/g' $1
	sed -i 's/RIO_STD_EXT_FEATS_PTR/RIO_ASSY_INF_EFB_PTR/g' $1
	sed -i 's/RIO_STD_EXT_FEATS_TYPE/RIO_EFB_T/g' $1
	sed -i 's/RIO_ASBLY_INFO_EXT_FEAT_PTR/RIO_ASSY_INF_EFB_PTR/g' $1
	sed -i 's/RIO_PROC_ELEM_FEAT_EXT_AS/RIO_PE_FEAT_EXT_ADDR/g' $1
	sed -i 's/RIO_PROC_ELEM_FEAT_/RIO_PE_FEAT_/g' $1

	sed -i 's/RIO_SOURCE_OPS/RIO_SRC_OPS_T/g' $1
	sed -i 's/RIO_SRC_OPS_CAR/RIO_SRC_OPS/g' $1

	sed -i 's/RIO_DEST_OPS/RIO_DST_OPS_T/g' $1
	sed -i 's/RIO_DST_OPS_CAR/RIO_DST_OPS/g' $1

	sed -i 's/RIO_RT_INFO_CAR/RIO_SW_RT_TBL_LIM/g' $1
	sed -i 's/RIO_RT_INFO_SIZE/RIO_SW_RT_TBL_LIM_MAX_DESTID/g' $1

	sed -i 's/RIO_DEV_ID_DEV_ID/RIO_DEV_IDENT_DEVI/g' $1
	sed -i 's/RIO_SWITCH_PORT_INF_PORT_TOTAL/RIO_SW_PORT_INF_TOT/g' $1
	sed -i 's/RIO_DEV_ID_DEV_VEN_ID/RIO_DEV_IDENT_VEND/g' $1
	sed -i 's/RIO_SWITCH_PORT_INF_CAR/RIO_SW_PORT_INF/g' $1
	sed -i 's/RIO_STD_SW_MC_INFO_CSR/RIO_SW_RT_TBL_LIM_MAX_DESTID/g' $1

	sed -i 's/RIO_BASE_DEVICE_ID_CSR/RIO_DEVID/g' $1
	sed -i 's/RIO_STD_HOST_BASE_ID_LOCK_HOST_BASE_ID/RIO_HOST_LOCK_DEVID/g' $1

	sed -i 's/RIO_COMPONENT_TAG_CSR/RIO_COMPTAG/g' $1

	sed -i 's/RIO_HOST_BASE_DEVICE_ID_LOCK_CSR/RIO_HOST_LOCK/g' $1

	sed -i 's/RIO_STD_RTE_CONF_DESTID_SEL_CSR/RIO_DEVID_RTE/g' $1

	sed -i 's/RIO_STD_RTE_DEF_PORT_CSR/RIO_DFLT_RTE/g' $1

	sed -i 's/RIO_STD_RTE_CONF_PORT_SEL_CSR/RIO_RTE/g' $1

	sed -i 's/RIO_STD_ROUTE_CFG_PORT_PORT0/RIO_RTE_PORT/g' $1

	sed -i 's/RIO_STD_MC_MASK_CFG_MASK_CMD/RIO_MC_MSK_CFG_CMD/g' $1
	sed -i 's/RIO_STD_MC_MASK_CFG_EG_PORT_NUM/RIO_MC_MSK_CFG_PT_NUM/g' $1
	sed -i 's/RIO_STD_MC_MASK_CFG_MC_MASK_NUM/RIO_MC_MSK_CFG_MSK_NUM/g' $1
	sed -i 's/RIO_STD_MC_MASK_CFG_MASK_CMD_WRITE_TO_VERIFY/RIO_MC_MSK_CFG_CMD_READ/g' $1
	sed -i 's/RIO_STD_MC_MASK_CFG_MASK_CMD_ADD_PORT/RIO_MC_MSK_CFG_CMD_ADD/g' $1
	sed -i 's/RIO_STD_MC_MASK_CFG_MASK_CMD_DEL_PORT/RIO_MC_MSK_CFG_CMD_DEL/g' $1
	sed -i 's/RIO_STD_MC_MASK_CFG_MASK_CMD_DEL_ALL_PORTS/RIO_MC_MSK_CFG_CMD_DEL_ALL/g' $1
	sed -i 's/RIO_STD_MC_MASK_CFG_MASK_CMD_ADD_ALL_PORTS/RIO_MC_MSK_CFG_CMD_ADD_ALL/g' $1
	sed -i 's/RIO_MC_MSK_CFG_CMD_DEL_PORT/RIO_MC_MSK_CFG_CMD_DEL/g' $1
	sed -i 's/RIO_MC_MSK_CFG_CMD_ADD_PORT/RIO_MC_MSK_CFG_CMD_ADD/g' $1
	sed -i 's/RIO_MC_MSK_CFG_CMD_DEL_ALL_PORTS/RIO_MC_MSK_CFG_CMD_DEL_ALL/g' $1
	sed -i 's/RIO_MC_MSK_CFG_CMD_ADD_ALL_PORTS/RIO_MC_MSK_CFG_CMD_ADD_ALL/g' $1

	sed -i 's/RIO_STD_MC_DESTID_CFG_DESTID_BASE_LT/RIO_MC_CON_SEL_DEV16/g' $1
	sed -i 's/RIO_STD_MC_DESTID_CFG_DESTID_BASE/RIO_MC_CON_SEL_DEV8/g' $1
	sed -i 's/RIO_STD_MC_DESTID_CFG_MASK_NUM_BASE/RIO_MC_CON_SEL_MASK/g' $1
	sed -i 's/RIO_STD_MC_DESTID_CFG/RIO_MC_CON_SEL/g' $1

	sed -i 's/RIO_STD_MC_DESTID_ASSOC_LARGE/RIO_MC_CON_OP_DEV16M/g' $1

	sed -i 's/RIO_STD_MC_DESTID_ASSOC_CMD_ADD_ASSOC/RIO_MC_CON_OP_CMD_ADD/g' $1
	sed -i 's/RIO_STD_MC_DESTID_ASSOC_CMD_DEL_ASSOC/RIO_MC_CON_OP_CMD_DEL/g' $1
	sed -i 's/RIO_STD_MC_DESTID_ASSOC_CMD/RIO_MC_CON_OP_CMD/g' $1

	sed -i 's/RIO_SWITCH_PORT_INFO/RIO_SW_PORT_INF_T/g' $1
	sed -i 's/RIO_PE_LLAYER_CONTROL_CSR/RIO_PE_LL_CTL/g' $1
	sed -i 's/RIO_ADDR_MODE/RIO_PE_ADDR_T/g' $1

	sed -i 's/RIO_STD_SW_MC_INFO_CSR/RIO_SW_MC_INF/g' $1

	sed -i 's/RIO_EXT_FEAT_PHYS_EP_FREE_SAER/RIO_EFB_T_SP_NOEP_SAER/g' $1
	sed -i 's/RIO_EXT_FEAT_PHYS_EP_FREE/RIO_EFB_T_SP_NOEP/g' $1
	sed -i 's/RIO_EXT_FEAT_PHYS_EP_SAER/RIO_EFB_T_SP_EP_SAER/g' $1
	sed -i 's/RIO_EXT_FEAT_PHYS_EP/RIO_EFB_T_SP_EP/g' $1

	sed -i 's/RIO_PORT_ERROR_STATUS/RIO_SPX_ERR_STAT_T/g' $1

	sed -i 's/RIO_PORT_N_LINK_MAINT_REQ_CSR/RIO_SPX_LM_REQ/g' $1
	sed -i 's/RIO_PORT_N_LINK_MAINT_REQ_CSR/RIO_SPX_LM_REQ/g' $1
	sed -i 's/RIO_SPX_LM_REQ_CMD_RESET/RIO_SPX_LM_REQ_CMD_RST_DEV/g' $1

	sed -i 's/RIO_PORT_N_LINK_MAINT_RESP_CSR/RIO_SPX_LM_RESP/g' $1
	sed -i 's/RIO_PORT_N_LINK_RESP_VALID/RIO_SPX_LM_RESP_VLD/g' $1

	sed -i 's/RIO_SPX_LM_LINK_STAT/RIO_SPX_LM_RESP_STAT_T/g' $1

	sed -i 's/RIO_PORT_N_LOCAL_ACKID_CSR/RIO_SPX_ACKID_ST/g' $1
	sed -i 's/RIO_SPX_ACKID_STAT_OUTBOUND/RIO_SPX_ACKID_ST_OUTB/g' $1
	sed -i 's/RIO_SPX_ACKID_STAT_OUTSTANDING/RIO_SPX_ACKID_ST_OUTST/g' $1
	sed -i 's/RIO_SPX_ACKID_STAT_INBOUND/RIO_SPX_ACKID_ST_INB/g' $1
	sed -i 's/RIO_SPX_ACKID_STAT_CLR_PKTS/RIO_SPX_ACKID_ST_CLR/g' $1
	sed -i 's/RIO_PORT_N_OUTBOUND_ACKID_MASK/RIO_SPX_ACKID_ST_OUTB/g' $1

	sed -i 's/RIO_PORT_N_CONTROL_CSR/RIO_SPX_CTL/g' $1
	sed -i 's/RIO_SPX_CTL_PORT_LOCKOUT/RIO_SPX_CTL_LOCKOUT/g' $1

	sed -i 's/RIO_SPX_CTL_1P25_SUP/RIO_SPX_CTL2_GB_1p25/g' $1
	sed -i 's/RIO_SPX_CTL_1P25_EN/RIO_SPX_CTL2_GB_1p25_EN/g' $1
	sed -i 's/RIO_SPX_CTL_2P5_SUP/RIO_SPX_CTL2_GB_2p5/g' $1
	sed -i 's/RIO_SPX_CTL_2P5_EN/RIO_SPX_CTL2_GB_2p5_EN/g' $1
	sed -i 's/RIO_SPX_CTL_3P125_SUP/RIO_SPX_CTL2_GB_3p125/g' $1
	sed -i 's/RIO_SPX_CTL_3P125_EN/RIO_SPX_CTL2_GB_3p125_EN/g' $1
	sed -i 's/RIO_SPX_CTL_5P0_SUP/RIO_SPX_CTL2_GB_5p0/g' $1
	sed -i 's/RIO_SPX_CTL_5P0_EN/RIO_SPX_CTL2_GB_5p0_EN/g' $1
	sed -i 's/RIO_SPX_CTL_6P25_SUP/RIO_SPX_CTL2_GB_6p25/g' $1
	sed -i 's/RIO_SPX_CTL_6P25_EN/RIO_SPX_CTL2_GB_6p25_EN/g' $1

	sed -i 's/RIO_SPX_CTL_OVER_PWIDTH/RIO_SPX_CTL_PTW_OVER/g' $1
	sed -i 's/RIO_SPX_CTL_INIT_PWIDTH/RIO_SPX_CTL_PTW_INIT/g' $1

	sed -i 's/RIO_SPX_CTL_INPUT_EN/RIO_SPX_CTL_INP_EN/g' $1
	sed -i 's/RIO_SPX_CTL_OUTPUT_EN/RIO_SPX_CTL_OTP_EN/g' $1

	sed -i 's/RIO_PORT_N_ERR_STAT_CSR/RIO_SPX_ERR_STAT/g' $1

	sed -i 's/RIO_STD_SW_MC_INFO_MAX_MASKS/RIO_SW_MC_INF_MC_MSK/g' $1

	sed -i 's/RIO_EXT_FEAT_ERR_RPT/RIO_EFB_T_EMHS/g' $1
	sed -i 's/RIO_EXT_FEAT_PER_LANE/RIO_EFB_T_LANE/g' $1
	sed -i 's/RIO_EXT_FEAT_VC_VOQ/RIO_EFB_T_V0Q/g' $1
	sed -i 's/RIO_EXT_FEAT_VC/RIO_EFB_T_VC/g' $1

	sed -i 's/RIO_SPX_ERR_DET_/RIO_EMHS_SPX_ERR_DET_/g' $1
	sed -i 's/RIO_SPX_ERR_RATE_ERR_/RIO_EMHS_SPX_RATE_/g' $1
	sed -i 's/RIO_SPX_ERR_RATE_ERR_RR/RIO_EMHS_SPX_RATE_RR/g' $1
	sed -i 's/RIO_SPX_ERR_RATE_ERR_RB/RIO_EMHS_SPX_RATE_RB/g' $1
	sed -i 's/RIO_SPX_ERR_THRESH_ERR_RFT/RIO_EMHS_SPX_THRESH_FAIL/g' $1

	sed -i 's/IS_RIO_PORT_N_ERR_STAT_PORT_OK/RIO_PORT_OK/g' $1
	sed -i 's/RIO_PORT_N_LINK_RESP_IS_VALID/RIO_SPX_LM_RESP_IS_VALID/g' $1

	sed -i 's/RIO_SPX_ERR_uint32_t_PORT_ERR/RIO_SPX_ERR_STAT_ERR/g' $1
	sed -i 's/RIO_SPX_ERR_uint32_t_INPUT_ERR_STOP/RIO_SPX_ERR_STAT_IES/g' $1
	sed -i 's/RIO_SPX_ERR_uint32_t_INPUT_RS/RIO_SPX_ERR_STAT_IRS/g' $1
	sed -i 's/RIO_SPX_ERR_uint32_t_OUTPUT_ERR_STOP/RIO_SPX_ERR_STAT_OES/g' $1
	sed -i 's/RIO_SPX_ERR_uint32_t_OUTPUT_RS/RIO_SPX_ERR_STAT_ORS/g' $1
	sed -i 's/RIO_SPX_ERR_uint32_t_OUTPUT_FAIL/RIO_SPX_ERR_STAT_FAIL/g' $1
	sed -i 's/RIO_SPX_ERR_uint32_t_OUTPUT_DROP/RIO_SPX_ERR_STAT_DROP/g' $1
	
	sed -i 's/RIO_SPX_ERR_STATUS_PORT_ERR/RIO_SPX_ERR_STAT_ERR/g' $1
	sed -i 's/RIO_SPX_ERR_STATUS_INPUT_ERR_STOP/RIO_SPX_ERR_STAT_IES/g' $1
	sed -i 's/RIO_SPX_ERR_STATUS_INPUT_RS/RIO_SPX_ERR_STAT_IRS/g' $1
	sed -i 's/RIO_SPX_ERR_STATUS_OUTPUT_ERR_STOP/RIO_SPX_ERR_STAT_OES/g' $1
	sed -i 's/RIO_SPX_ERR_STATUS_OUTPUT_RS/RIO_SPX_ERR_STAT_ORS/g' $1
	sed -i 's/RIO_SPX_ERR_STATUS_OUTPUT_FAIL/RIO_SPX_ERR_STAT_FAIL/g' $1
	sed -i 's/RIO_SPX_ERR_STATUS_OUTPUT_DROP/RIO_SPX_ERR_STAT_DROP/g' $1
	
	sed -i 's/STATUS/uint32_t/g' $1
}

for i in inc/*.h; do
	make_changes ${i}
done

for i in src/*.c; do
	make_changes ${i}
done


